apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2023-08-27T22:26:55Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: kotsadm-rqlite
    kots.io/backup: velero
    kots.io/kotsadm: "true"
  name: kotsadm-rqlite-kotsadm-rqlite-0
  namespace: securiti
  resourceVersion: "648"
  uid: fd4e64dd-efe6-4ee3-8a01-f0ea256ce821
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
status:
  phase: Pending