apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2023-08-28T12:17:38Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: epod-pg
    app.kubernetes.io/name: postgresql
  name: data-epod-pg-postgresql-0
  namespace: default
  resourceVersion: "657"
  uid: edae60e0-6234-481d-b2cb-1fa43e8af602
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
status:
  phase: Pending